site:
  title: Corteza Docs
  url: https://docs.cortezaproject.org
  start_page: corteza-docs::index.adoc
  robots: allow

content:
  sources:
  - url: https://github.com/cortezaproject/corteza-docs
    branches: [ 2019.12.x, 2020.6.x, 2020.9.x, 2020.12.x ]
    start_path: src

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./antora/ui

output:
  clean: true
  dir: dist

asciidoc:
  attributes:
    experimental: true
    doctype: book
  extensions:
    - asciidoctor-kroki
